import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Rubik } from "next/font/google";
import Authprovider from "../component/AuthProvider/Authprovider";
import  {ReduxProvider} from '../Provider';



// fonts
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rubik"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
  
    <html lang="en">
      
      <body className={`${rubik.variable}`}>
      <ReduxProvider>
        <Authprovider> {children}</Authprovider>
      </ReduxProvider>
        </body>
        
    </html>
  );
}
